name: TECCOD

services:
  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  dashboards:
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    profiles: ["dashboards"]
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      OPENSEARCH_HOSTS: '["http://opensearch:9200"]'
      DISABLE_SECURITY_DASHBOARDS_PLUGIN: "true"
      SERVER_HOST: "0.0.0.0"
    ports:
      - "5601:5601"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:5601/api/status >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: os-fastapi-web
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      APP_HOST: "0.0.0.0"
      APP_PORT: "8000"
      OS_HOST: "opensearch"
      OS_PORT: "9200"
      OS_USER: ""
      OS_PASSWORD: ""
      OS_USE_SSL: "false"
      OS_VERIFY_CERTS: "false"
      OS_INDEX_NAME: "documents"
      CONTENT_TYPES: "article,blog,news,report"
    ports:
      - "8000:8000"
    networks:
      - opensearch-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/health >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

networks:
  opensearch-net:

volumes:
  opensearch-data:
